// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqglI6-g01g9LCtdZeg4AVtBxmEBEvFUM',
    appId: '1:142232890681:web:1a916db063f72664a0cce8',
    messagingSenderId: '142232890681',
    projectId: 'flutter-chat-5e47b',
    authDomain: 'flutter-chat-5e47b.firebaseapp.com',
    storageBucket: 'flutter-chat-5e47b.appspot.com',
    measurementId: 'G-67NPE61BVK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN6F0lZCcLk1DzD7gZvs_Sf0L0of2zmtk',
    appId: '1:142232890681:android:bcd71ae5e398bf8fa0cce8',
    messagingSenderId: '142232890681',
    projectId: 'flutter-chat-5e47b',
    storageBucket: 'flutter-chat-5e47b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGf25x_ZtnSfJDTSVUss9nVowlqwT31xc',
    appId: '1:142232890681:ios:5ceea0c92fd5526aa0cce8',
    messagingSenderId: '142232890681',
    projectId: 'flutter-chat-5e47b',
    storageBucket: 'flutter-chat-5e47b.appspot.com',
    iosClientId: '142232890681-cq39qdireng7uqv5t7t3m7sgsi289pdt.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGf25x_ZtnSfJDTSVUss9nVowlqwT31xc',
    appId: '1:142232890681:ios:5ceea0c92fd5526aa0cce8',
    messagingSenderId: '142232890681',
    projectId: 'flutter-chat-5e47b',
    storageBucket: 'flutter-chat-5e47b.appspot.com',
    iosClientId: '142232890681-cq39qdireng7uqv5t7t3m7sgsi289pdt.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
